### ISSUE TITLE
Replace bed spawn-setting?

### ISSUE THREAD

**Issue by exaskye** [elytra/Fondue6#10]
It's almost always day on a server, so this doesn't work very well, and it makes setting your spawn maybe *too* cheap.

I had an idea a while ago to generate periodic Crying Obsidian obelisks, which can't be broken and allow you to set your spawn, but only where there is an obelisk. They'd generate in a regular pattern, making a sort of grid, but would be fairly far apart (maybe 256 blocks?). The grid should be of non-squares and/or not axis-aligned so it seems irregular.

The first obelisk would be placed at world spawn, and the rest would be relative to it. By default everyone would attune to the world spawn obelisk, and attuning to a new one would be a simple right-click.

Put a reaction on this issue to vote. If you leave :-1:, also leave a comment explaining why.

If you're for removing the ability for beds to set spawn, but against the obelisk idea, leave a :confused: reaction.

**Comment by asiekierka** [comment]
I think there should be *some* way of setting your spawn. Not saying that beds are said way, but it will get very tiresome otherwise.

One way to fix this would be to add a cooldown on setting spawns, but that's a bit... boring? Obelisks sound like a fair idea.

**Comment by exaskye** [comment]
Yes, obviously there should be a way to set your spawn. This issue isn't about removing the ability to set your spawn completely, it's about moving that function to some other block.

I'll edit the title to clarify that.

**Comment by falkreon** [comment]
Crying obelisks makes a lot of sense. Let's move it out to AT LEAST 500m, and then offset the position in a gaussian fashion with a magnitude of half that, ~250 or so. This makes sure that there's roughly even coverage on the map, and yet stones would be anywhere from 500m - 1km apart and unaligned. That's enough clearing that routing trains between obelisks/bases starts to become worth it.

Edit: Whoops, I did math bad. If they started 500m apart, 250m could wind up putting them next to each other. Go 1/4, which makes it anywhere from 250 to 750 blocks? Still feels super close.
