### ISSUE TITLE
Disable/Remove TechReborn Water Mills

### ISSUE THREAD

**Issue by falkreon** [elytra/Fondue6#17]
Passive RF water mills shouldn't be a thing. If they're not already disabled, we should do that.

**Comment by exaskye** [comment]
Looks like TechReborn has no simple way to disable their machines. We'll need to use MineTweaker or add support to the Fondue mod.

**Comment by darkevilmac** [comment]
Should Windmills also be disabled?

**Comment by exaskye** [comment]
Yes, as should solar.
